source "https://rubygems.org"

gem "selenium-cucumber" , "~> 2.1.4"
gem "capybara"
gem "configatron"
gem "chromedriver-helper"
gem "selenium-webdriver" , "2.53.4"
gem "calabash-cucumber" , "~> 0.19.0"
gem "calabash-android" , "~> 0.7.3"
gem "run_loop", "~> 2.1.6"
gem "touch_action"
gem "jenkins_api_client"
